[build-system]
requires = [
    "setuptools>=77",
    "pybind11>=2.10",
]
build-backend = "setuptools.build_meta"

[project]
name = "axionbloch"
version = "0.1.2"
description = "Simulation tool for axion-induced spin dynamics."

authors = [
    { name = "Yuzhe Zhang", email = "yuhzhang@uni-mainz.de" }
]

readme = "README.md"

license = "MIT"
license-files = ["LICENSE"]

requires-python = ">=3.9"

dependencies = [
    "numpy",
    "matplotlib",
    "astropy",
    "scipy",
    "h5py",
]

[tool.setuptools]
zip-safe = false

[tool.setuptools.package-data]
axionbloch = ["data/**/*"]

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-* cp313-*"
skip = "*-musllinux_*"

[tool.cibuildwheel.linux]
before-all = "yum install -y libgomp || apt-get install -y libgomp1 || true"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]