"""Reproduce the four periodic-modulation panels in Gramolin spectral signature paper."""

from pathlib import Path
import sys
import textwrap

import matplotlib

# # Regular interactive mode: try TkAgg, otherwise fall back to Agg.
# try:
#     matplotlib.use("TkAgg")
#     interactive = True
# except Exception:
#     matplotlib.use("Agg")
#     interactive = False

import matplotlib.pyplot as plt
import numpy as np
from astropy import units as unit

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from axionbloch.MilkyWayAxionHalo import MilkyWayAxionHalo
from axionbloch.Station import Boston

FIGURE_DIR = Path(__file__).resolve().parent / "figures"
FIGURE_DIR.mkdir(exist_ok=True)

station = Boston
axion = MilkyWayAxionHalo(nu_a=1.0 * unit.MHz)

# Equation (34) of Phys. Rev. D 105, 035029 (2022). The time origin is
# January 1; the maximum near June 1 occurs at tau = t_y + 72.4 days.
annual_days = np.linspace(0, 365, 365 + 1)
v_sun = 233 * unit.km / unit.s
v_earth = 29.8 * unit.km / unit.s
eta = 0.982
omega_year = 2 * np.pi / 365
vernal_equinox_day = 31 + 28 + 19
tau = vernal_equinox_day + 72.4
v_lab_annual = np.sqrt(
    v_sun**2
    + v_earth**2
    + eta * v_sun * v_earth * np.cos(omega_year * (annual_days - tau))
)

# Equations (35)-(37) for January 1 at Boston University. The Station object
# supplies the signed latitude and longitude specified in the figure caption.
daily_hours = np.linspace(0, 24, 145)
daily_days = daily_hours / 24
latitude = station.location.lat.to_value(unit.rad)
longitude = station.location.lon.to_value(unit.rad)
b_0 = 0.7589
b_1 = 0.6512
psi = -3.5336
phase = longitude + psi
omega_day = 2 * np.pi / 0.9973
daily_argument = omega_day * daily_days + phase

cos_alpha = {
    "North": (b_0 * np.cos(latitude) - b_1 * np.sin(latitude) * np.cos(daily_argument)),
    "West": b_1 * np.sin(daily_argument),
    "Zenith": (
        b_0 * np.sin(latitude) + b_1 * np.cos(latitude) * np.cos(daily_argument)
    ),
}
styles = {
    "North": {"color": "red", "linestyle": "-"},
    "West": {"color": "blue", "linestyle": "--"},
    "Zenith": {"color": "green", "linestyle": "-."},
}

v_lab_january_1 = np.full_like(daily_hours, v_lab_annual[0].value) * v_lab_annual.unit

fig, axes = plt.subplots(1, 2, figsize=(14 / 2.54, 6 / 2.54), dpi=300)
fig.patch.set_facecolor("white")
ax_a, ax_b = axes

ax_a.plot(
    annual_days,
    v_lab_annual.to_value(unit.km / unit.s),
    color="black",
)
ax_a.set_ylabel("$v_\\mathrm{lab}$ (km/s)")
month_starts = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334]
ax_a.set_xticks(month_starts)
ax_a.set_xticklabels(
    [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
    ],
    rotation=60,
    ha="center",
)
ax_a.set_xlim(0, 365)

for label in cos_alpha:
    ax_b.plot(
        daily_hours,
        cos_alpha[label],
        label=label,
        **styles[label],
    )

ax_b.axhline(0, color="0.65", linewidth=0.6, zorder=0)
ax_b.set_ylabel("$\\cos\\alpha$")
ax_b.set_ylim(-1.05, 1.05)

ax_b.set_xlim(0, 24)
ax_b.set_xticks([0, 6, 12, 18, 24])
ax_b.set_xlabel("Time (hour)\nfrom 2022-01-01 00:00 Boston local time")

ax_b.legend(loc="lower right", frameon=False, fontsize=7)
for panel_label, ax in zip(("a", "b"), axes.flat):
    ax.text(
        -0.18,
        1.02,
        f"({panel_label})",
        transform=ax.transAxes,
        ha="left",
        va="bottom",
    )
# caption discarded per request

# Watermark follows examples/example_matplotlib.py.
script_path = Path(__file__).resolve()
figure_width_points = fig.get_size_inches()[0] * 72
approximate_character_width_points = 0.6 * 4
maximum_characters = int(figure_width_points / approximate_character_width_points)
watermark = textwrap.fill(
    f"Generated by: {script_path}",
    width=maximum_characters,
)
fig.text(
    0.02,
    0.008,
    watermark,
    fontsize=6,
    color="gray",
    wrap=True,
)

fig.subplots_adjust(
    left=0.102,
    right=0.98,
    top=0.904,
    bottom=0.242,
    wspace=0.32,
    hspace=0.38,
)

output_path = FIGURE_DIR / "MW-axion-annual-daily-modulations.pdf"
fig.savefig(output_path, facecolor="white", transparent=False)
plt.show()


# plt.close(fig)

print(f"Saved {output_path}")
print(
    "Annual speed range:",
    f"{np.min(v_lab_annual).to_value(unit.km / unit.s):.2f}",
    "to",
    f"{np.max(v_lab_annual).to_value(unit.km / unit.s):.2f}",
    "km/s",
)
