"""Long-time stochastic axion-signal amplitude check.

This script tests the late-time signal amplitude for

    s(t) = [1 - exp(-t / (x T2star))]**x
           * gamma * B * T2star * sqrt(tau_a / (tau_a + T2star)).

Defaults follow the 2026-07-07 long-time scan:

* nu_a = 1 MHz;
* T2 = 10 s;
* T2star = (0.01, 0.03, 0.1, 0.3, 1, 3, 10, 30, 100) tau_a;
* rate = 20 / min(T2, T2star, tau_a);
* duration = 10 max(T2, T2star, tau_a), unless an explicit duration
  override is supplied.

The runtime estimate uses the method implemented in ``SimuTools.py``:

    numSteps = ceil(duration * rate) - 1
    t_setFields = T_SETFIELD_S * numFields * (numSteps + 1)
    t_trjry = T_SIMUSTEP_S * numSteps * magnet.numPt * numFields
    t_total = t_setFields + t_trjry

For batched runs, the estimate is summed over all batches.
"""

from __future__ import annotations

import argparse
import csv
import gc
import json
import sys
import textwrap
import time
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import matplotlib

if "--show" not in sys.argv:
    matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from astropy import units as unit

from axionbloch.SimuTools import T_SETFIELD_S, T_SIMUSTEP_S
from axionbloch.dependency import PI
from test_signal_growth_overtime import make_case, run_case, signal_formula


OUTPUT_DIR = SCRIPT_DIR / "outputs"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--frequency-Hz", type=float, default=1e6)
    parser.add_argument("--T2-seconds", type=float, default=10.0)
    parser.add_argument(
        "--T2star-over-taua",
        nargs="+",
        type=float,
        default=[0.01, 0.03, 0.1, 0.3, 1.0, 3.0, 10.0, 30.0, 100.0],
    )
    parser.add_argument("--g-ann", type=float, default=1e-11)
    parser.add_argument("--num-fields", type=int, default=1000)
    parser.add_argument("--batch-size", type=int, default=50)
    parser.add_argument("--duration-multiplier", type=float, default=10.0)
    parser.add_argument(
        "--duration-seconds",
        type=float,
        default=None,
        help="Explicit simulation duration in seconds.",
    )
    parser.add_argument(
        "--duration-times-max-T2star-taua",
        type=float,
        default=None,
        help="Set duration to this factor times max(T2star, tau_a).",
    )
    parser.add_argument(
        "--duration-times-min-T2star-T2-taua",
        type=float,
        default=None,
        help="Set duration to this factor times min(T2star, T2, tau_a).",
    )
    parser.add_argument("--points-per-short-time", type=float, default=20.0)
    parser.add_argument("--seed", type=int, default=700)
    parser.add_argument("--max-errorbars", type=int, default=80)
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=OUTPUT_DIR / "long-time-signal-amplitude",
    )
    parser.add_argument("--estimate-only", action="store_true")
    parser.add_argument("--show", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if args.frequency_Hz <= 0:
        parser.error("--frequency-Hz must be positive.")
    if args.T2_seconds <= 0:
        parser.error("--T2-seconds must be positive.")
    if any(value <= 0 for value in args.T2star_over_taua):
        parser.error("--T2star-over-taua values must be positive.")
    if args.g_ann <= 0:
        parser.error("--g-ann must be positive.")
    if args.num_fields < 1:
        parser.error("--num-fields must be positive.")
    if args.batch_size < 1 or args.batch_size > args.num_fields:
        parser.error("--batch-size must be between 1 and --num-fields.")
    if args.duration_multiplier <= 0:
        parser.error("--duration-multiplier must be positive.")
    if args.duration_seconds is not None and args.duration_seconds <= 0:
        parser.error("--duration-seconds must be positive.")
    if (
        args.duration_times_max_T2star_taua is not None
        and args.duration_times_max_T2star_taua <= 0
    ):
        parser.error("--duration-times-max-T2star-taua must be positive.")
    if (
        args.duration_times_min_T2star_T2_taua is not None
        and args.duration_times_min_T2star_T2_taua <= 0
    ):
        parser.error("--duration-times-min-T2star-T2-taua must be positive.")
    if args.points_per_short_time <= 0:
        parser.error("--points-per-short-time must be positive.")
    if args.max_errorbars < 1:
        parser.error("--max-errorbars must be positive.")
    return args


def add_script_watermark(fig: matplotlib.figure.Figure) -> None:
    script_path = str(Path(__file__).resolve())
    text = "Generated by: " + script_path
    fig.text(
        0.01,
        0.01,
        textwrap.fill(text, width=120),
        ha="left",
        va="bottom",
        fontsize=6,
        color="0.45",
    )


def batch_sizes(total_fields: int, batch_size: int) -> list[int]:
    sizes = []
    completed = 0
    while completed < total_fields:
        size = min(batch_size, total_fields - completed)
        sizes.append(size)
        completed += size
    return sizes


def estimate_runtime(params, total_fields: int, batch_size: int) -> dict[str, float]:
    """Estimate runtime without constructing the full magnet packet grid."""
    duration = params["duration"].to(unit.s)
    rate = params["rate"].to(unit.Hz)
    sample = params["sample"]
    magnet = params["magnet"]
    num_steps = int(np.ceil((duration * rate).to_value(unit.one))) - 1
    raw_num_pt = abs(
        (
            duration
            * 2
            * magnet.B0_nW
            * sample.gamma
            / (2 * PI)
        ).to_value(unit.one)
    )
    num_pt = 1 if raw_num_pt <= 1 else int(raw_num_pt + 11)
    estimated_setfields_s = T_SETFIELD_S * total_fields * (num_steps + 1)
    estimated_trjry_s = T_SIMUSTEP_S * num_steps * num_pt * total_fields
    estimated_total_s = estimated_setfields_s + estimated_trjry_s
    nu_l_abs_max = abs(
        (sample.gamma / (2 * PI) * magnet.B0_nW).to(unit.Hz)
    )
    detuning_threshold = 20 * nu_l_abs_max
    return {
        "estimated_setFields_s": estimated_setfields_s,
        "estimated_trjry_s": estimated_trjry_s,
        "estimated_total_s": estimated_total_s,
        "estimated_total_min": estimated_total_s / 60.0,
        "num_batches": len(batch_sizes(total_fields, batch_size)),
        "rate_Hz": rate.to_value(unit.Hz),
        "duration_s": duration.to_value(unit.s),
        "numSteps": num_steps,
        "numPt": num_pt,
        "timeStep_s": (1 / rate).to_value(unit.s),
        "detuning_warning_threshold_Hz": detuning_threshold.to_value(unit.Hz),
        "rate_over_detuning_threshold": (
            rate / detuning_threshold
        ).to_value(unit.one),
    }


def run_batched_case_with_signal_std(
    params,
    total_fields: int,
    batch_size: int,
    seed: int,
    verbose: bool,
):
    """Run batches and combine RMS plus std(|M_perp|) exactly."""
    sum_mean_m = None
    sum_second_m = None
    sum_mean_q = None
    sum_second_q = None
    completed = 0
    aggregate_entry = None

    while completed < total_fields:
        current_size = min(batch_size, total_fields - completed)
        batch_params = dict(params)
        batch_params["numFields"] = current_size
        batch_params["rand_seed"] = seed + completed
        simulations = run_case(batch_params, field_mode="stochastic", verbose=verbose)
        entry = simulations.pool[0]
        simu = entry.simu

        mean_m = np.asarray(simu.Mxy_mrs)
        std_m = np.asarray(simu.Mxy_srs)
        second_m = std_m**2 + mean_m**2

        mean_q = np.asarray(simu.Mxy_rms) ** 2
        std_q = np.asarray(simu.Mxy_rss) ** 2
        second_q = std_q**2 + mean_q**2

        if sum_mean_m is None:
            sum_mean_m = current_size * mean_m
            sum_second_m = current_size * second_m
            sum_mean_q = current_size * mean_q
            sum_second_q = current_size * second_q
            aggregate_entry = entry
        else:
            sum_mean_m += current_size * mean_m
            sum_second_m += current_size * second_m
            sum_mean_q += current_size * mean_q
            sum_second_q += current_size * second_q

        completed += current_size
        print(f"    completed fields: {completed}/{total_fields}", flush=True)
        simu.cleanup()
        del simulations
        gc.collect()

    mean_m = sum_mean_m / total_fields
    variance_m = np.maximum(sum_second_m / total_fields - mean_m**2, 0.0)
    mean_q = sum_mean_q / total_fields
    variance_q = np.maximum(sum_second_q / total_fields - mean_q**2, 0.0)

    aggregate_entry.simu.Mxy_mrs = mean_m
    aggregate_entry.simu.Mxy_srs = np.sqrt(variance_m)
    aggregate_entry.simu.Mxy_rms = np.sqrt(mean_q)
    # keepMeanStd stores sqrt(std(Mxy**2)).
    aggregate_entry.simu.Mxy_rss = variance_q**0.25
    aggregate_entry.params["numFields"] = total_fields
    return aggregate_entry


def make_long_time_case(args: argparse.Namespace, multiplier: float):
    frequency = args.frequency_Hz * unit.Hz
    T2 = args.T2_seconds * unit.s
    probe_params = make_case(
        frequency=frequency,
        ratio=1.0,
        T2_over_T2star=2.0,
        num_fields=1,
        duration_factor=1.0,
        points_per_short_time=args.points_per_short_time,
        g_ann=args.g_ann,
        numerical_magnetization_scale=1.0,
        field_mode="stochastic",
        seed=args.seed,
    )
    tau_a = probe_params["axion"].tau_a_est.to(unit.s)
    T2star = multiplier * tau_a
    if T2star >= T2:
        return None, {
            "T2star_over_taua": multiplier,
            "tau_a_s": tau_a.to_value(unit.s),
            "T2star_s": T2star.to_value(unit.s),
            "T2_s": T2.to_value(unit.s),
            "skip_reason": "combined T2star must be smaller than fixed T2",
        }

    ratio = (tau_a / T2star).to_value(unit.one)
    T2_over_T2star = (T2 / T2star).to_value(unit.one)
    if args.duration_seconds is not None:
        duration = args.duration_seconds * unit.s
    elif args.duration_times_max_T2star_taua is not None:
        duration = args.duration_times_max_T2star_taua * max(T2star, tau_a)
    elif args.duration_times_min_T2star_T2_taua is not None:
        duration = args.duration_times_min_T2star_T2_taua * min(T2star, T2, tau_a)
    else:
        duration = args.duration_multiplier * max(T2, T2star, tau_a)
    rate = args.points_per_short_time / min(T2, T2star, tau_a)
    params = make_case(
        frequency=frequency,
        ratio=ratio,
        T2_over_T2star=T2_over_T2star,
        num_fields=min(args.batch_size, args.num_fields),
        duration_factor=(duration / T2star).to_value(unit.one),
        points_per_short_time=args.points_per_short_time,
        g_ann=args.g_ann,
        numerical_magnetization_scale=1.0,
        field_mode="stochastic",
        seed=args.seed,
    )
    params["rate"] = rate.to(unit.Hz)
    params["duration"] = duration.to(unit.s)
    return params, None


def analyze_long_time_case(entry, multiplier: float) -> dict[str, object]:
    simu = entry.simu
    tau_a = simu.axion.tau_a_est.to(unit.s)
    T2star = simu.T2star.to(unit.s)
    time_axis = np.arange(len(simu.Mxy_rms)) * simu.timeStep
    x_original = 0.5 * (
        1.0 + (tau_a / (tau_a + T2star)).to_value(unit.one)
    )
    expected = signal_formula(
        time_axis,
        simu.sample.gamma,
        entry.params["B_a_rms"],
        tau_a,
        T2star,
        x_original,
    )
    return {
        "T2star_over_taua": multiplier,
        "frequency_Hz": simu.axion.nu_a.to_value(unit.Hz),
        "tau_a_s": tau_a.to_value(unit.s),
        "T2star_s": T2star.to_value(unit.s),
        "T2_s": simu.sample.T2.to_value(unit.s),
        "duration_s": simu.duration.to_value(unit.s),
        "rate_Hz": simu.rate.to_value(unit.Hz),
        "numSteps": int(simu.numSteps),
        "numPt": int(simu.magnet.numPt),
        "num_fields": entry.params["numFields"],
        "x_original": x_original,
        "B_rms_T": entry.params["B_a_rms"].to_value(unit.T),
        "time_s": time_axis.to_value(unit.s),
        "rms": np.asarray(simu.Mxy_rms),
        "signal_std": np.asarray(simu.Mxy_srs),
        "expected": expected,
        "final_rms": float(np.asarray(simu.Mxy_rms)[-1]),
        "final_std": float(np.asarray(simu.Mxy_srs)[-1]),
        "final_expected": float(expected[-1]),
        "asymptotic_expected": float(expected[-1] / (
            (1 - np.exp(
                -time_axis[-1] / (x_original * T2star)
            ).to_value(unit.one)) ** x_original
        )),
    }


def asymptotic_expected_for_params(params) -> float:
    """Return the t -> infinity stochastic RMS formula for one case."""
    tau_a = params["axion"].tau_a_est.to(unit.s)
    T2star = (tau_a / params["key_info"]["tau_a_over_T2star"]).to(unit.s)
    return float(asymptotic_expected_curve(params, np.array([T2star / tau_a]))[0])


def asymptotic_expected_curve(params, ratios: np.ndarray) -> np.ndarray:
    """Return the stochastic t -> infinity formula over T2star/tau_a."""
    tau_a = params["axion"].tau_a_est.to(unit.s)
    T2star = ratios * tau_a
    values = (
        np.abs(params["sample"].gamma)
        * params["B_a_rms"]
        * T2star
        * np.sqrt((tau_a / (tau_a + T2star)).to_value(unit.one))
    ).to_value(unit.rad)
    return values


def save_time_series(results: list[dict[str, object]], prefix: Path) -> list[Path]:
    paths = []
    for result in results:
        tag = f"T2star-{result['T2star_over_taua']:g}taua".replace(".", "p")
        path = prefix.parent / f"{prefix.name}-{tag}.csv"
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["time_s", "rms", "signal_std", "expected"])
            for row in zip(
                result["time_s"],
                result["rms"],
                result["signal_std"],
                result["expected"],
            ):
                writer.writerow(row)
        paths.append(path)
    return paths


def save_summary(
    results: list[dict[str, object]],
    skipped: list[dict[str, object]],
    estimates: list[dict[str, object]],
    prefix: Path,
) -> Path:
    path = prefix.parent / f"{prefix.name}-summary.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    serializable_results = []
    for result in results:
        serializable_results.append(
            {
                key: value
                for key, value in result.items()
                if key not in {"time_s", "rms", "signal_std", "expected"}
            }
        )
    payload = {
        "runtime_estimation_method": {
            "numSteps": "ceil(duration * rate) - 1",
            "t_setFields_s": "T_SETFIELD_S * numFields * (numSteps + 1)",
            "t_trjry_s": "T_SIMUSTEP_S * numSteps * magnet.numPt * numFields",
            "t_total_s": "t_setFields_s + t_trjry_s; summed over batches",
        },
        "results": serializable_results,
        "skipped": skipped,
        "estimates": estimates,
    }
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return path


def plot_results(
    results: list[dict[str, object]],
    skipped: list[dict[str, object]],
    prefix: Path,
    max_errorbars: int,
) -> matplotlib.figure.Figure | None:
    if not results:
        return None
    fig, axes = plt.subplots(
        len(results),
        1,
        figsize=(7.2, 2.5 * len(results)),
        sharex=False,
        constrained_layout=True,
        squeeze=False,
    )
    for result, ax in zip(results, axes[:, 0]):
        time_s = result["time_s"]
        rms = result["rms"]
        signal_std = result["signal_std"]
        expected = result["expected"]
        step = max(1, int(np.ceil(len(time_s) / max_errorbars)))
        ax.plot(time_s, rms, color="black", linewidth=1.2, label="simulation RMS")
        ax.errorbar(
            time_s[::step],
            rms[::step],
            yerr=signal_std[::step],
            fmt="none",
            ecolor="tab:blue",
            elinewidth=0.8,
            alpha=0.45,
            capsize=1.5,
            label="std of signal",
        )
        ax.plot(
            time_s,
            expected,
            color="tab:orange",
            linestyle="--",
            linewidth=1.3,
            label="formula",
        )
        ax.set_title(
            rf"$T_2^*={result['T2star_over_taua']:g}\,\tau_a$, "
            rf"$T_2={result['T2_s']:g}$ s, "
            rf"$\tau_a={result['tau_a_s']:.3g}$ s"
        )
        ax.set_xlabel("time (s)")
        ax.set_ylabel(r"$M_\perp/M_\mathrm{eqb}$")
        ax.grid(alpha=0.25)
        ax.legend(fontsize=8)

    if skipped:
        skipped_text = "; ".join(
            f"{item['T2star_over_taua']:g} tau_a skipped: {item['skip_reason']}"
            for item in skipped
        )
        fig.suptitle(skipped_text, fontsize=9)
    add_script_watermark(fig)
    path = prefix.parent / f"{prefix.name}.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220, facecolor="white")
    return fig


def plot_final_amplitude(
    results: list[dict[str, object]],
    case_records: list[dict[str, object]],
    skipped: list[dict[str, object]],
    prefix: Path,
) -> matplotlib.figure.Figure | None:
    valid_records = [
        record for record in case_records if record.get("params") is not None
    ]
    if not valid_records and not results:
        return None

    fig, ax = plt.subplots(figsize=(6.4, 4.2), constrained_layout=True)
    if valid_records:
        valid_ratios = np.array(
            [record["multiplier"] for record in valid_records], dtype=float
        )
        formula_values = np.array(
            [
                asymptotic_expected_for_params(record["params"])
                for record in valid_records
            ]
        )
        order = np.argsort(valid_ratios)
        smooth_ratios = np.logspace(
            np.log10(valid_ratios[order][0]),
            np.log10(valid_ratios[order][-1]),
            300,
        )
        smooth_formula = asymptotic_expected_curve(
            valid_records[order[0]]["params"],
            smooth_ratios,
        )
        ax.plot(
            smooth_ratios,
            smooth_formula,
            color="tab:orange",
            linestyle="--",
            linewidth=1.3,
            label=r"formula, $t\to\infty$",
        )
        ax.scatter(
            valid_ratios[order],
            formula_values[order],
            color="tab:orange",
            s=18,
            zorder=3,
            label="requested grid",
        )

    if results:
        sim_ratios = np.array(
            [result["T2star_over_taua"] for result in results], dtype=float
        )
        final_rms = np.array([result["final_rms"] for result in results])
        final_std = np.array([result["final_std"] for result in results])
        ax.errorbar(
            sim_ratios,
            final_rms,
            yerr=final_std,
            fmt="o",
            color="black",
            ecolor="tab:blue",
            elinewidth=0.9,
            capsize=2,
            label="simulation final RMS",
        )

    for item in skipped:
        ax.axvline(
            item["T2star_over_taua"],
            color="0.7",
            linestyle=":",
            linewidth=0.9,
        )

    ax.set_xscale("log")
    ax.set_xlabel(r"$T_2^*/\tau_a$")
    ax.set_ylabel(r"final $M_\perp/M_\mathrm{eqb}$")
    ax.grid(alpha=0.25, which="both")
    ax.legend(fontsize=8)
    add_script_watermark(fig)
    path = prefix.parent / f"{prefix.name}-final-amplitude.png"
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=220, facecolor="white")
    return fig


def main() -> None:
    args = parse_args()
    prefix = args.output_prefix
    prefix.parent.mkdir(parents=True, exist_ok=True)

    results = []
    skipped = []
    estimates = []
    case_records = []
    total_cases = len(args.T2star_over_taua)
    for case_index, multiplier in enumerate(args.T2star_over_taua, start=1):
        params, skip = make_long_time_case(args, multiplier)
        if skip is not None:
            skipped.append(skip)
            case_records.append(
                {
                    "case_index": case_index,
                    "multiplier": multiplier,
                    "params": None,
                    "estimate": None,
                }
            )
            print(
                f"[{case_index}/{total_cases}] T2star={multiplier:g} tau_a skipped: "
                f"{skip['skip_reason']}",
                flush=True,
            )
            continue

        estimate = estimate_runtime(params, args.num_fields, args.batch_size)
        estimate["T2star_over_taua"] = multiplier
        estimates.append(estimate)
        case_records.append(
            {
                "case_index": case_index,
                "multiplier": multiplier,
                "params": params,
                "estimate": estimate,
            }
        )
        print(
            f"[{case_index}/{total_cases}] T2star={multiplier:g} tau_a, "
            f"duration={estimate['duration_s']:.4g} s, "
            f"rate={estimate['rate_Hz']:.4g} Hz, "
            f"numSteps={estimate['numSteps']}, numPt={estimate['numPt']}, "
            f"estimated={estimate['estimated_total_min']:.3g} min, "
            f"rate/detuning-threshold="
            f"{estimate['rate_over_detuning_threshold']:.3g}",
            flush=True,
        )

    estimated_total_min = sum(
        estimate["estimated_total_min"] for estimate in estimates
    )
    print(
        f"Estimated total runtime for valid requested cases: "
        f"{estimated_total_min:.3g} min = {estimated_total_min / 60:.3g} h",
        flush=True,
    )
    if args.estimate_only:
        summary_path = save_summary(results, skipped, estimates, prefix)
        final_figure = plot_final_amplitude(results, case_records, skipped, prefix)
        if final_figure is not None:
            plt.close(final_figure)
            print(
                f"Saved formula summary: "
                f"{prefix.parent / (prefix.name + '-final-amplitude.png')}",
                flush=True,
            )
        print(f"Saved summary: {summary_path}", flush=True)
        return

    for record in case_records:
        params = record["params"]
        if params is None:
            continue
        case_index = record["case_index"]
        multiplier = record["multiplier"]

        tic = time.perf_counter()
        entry = run_batched_case_with_signal_std(
            params,
            args.num_fields,
            args.batch_size,
            args.seed + 10_000 * case_index,
            args.verbose,
        )
        result = analyze_long_time_case(entry, multiplier)
        results.append(result)
        entry.simu.cleanup()
        del entry
        gc.collect()
        print(
            f"    actual runtime={(time.perf_counter() - tic) / 60:.3g} min; "
            f"final RMS={result['final_rms']:.4g}, "
            f"formula={result['final_expected']:.4g}",
            flush=True,
        )

    csv_paths = save_time_series(results, prefix)
    summary_path = save_summary(results, skipped, estimates, prefix)
    figure = plot_results(results, skipped, prefix, args.max_errorbars)
    final_figure = plot_final_amplitude(results, case_records, skipped, prefix)
    if figure is not None and args.show:
        plt.show()
    elif figure is not None:
        plt.close(figure)
    if final_figure is not None and not args.show:
        plt.close(final_figure)

    print(f"Saved summary: {summary_path}", flush=True)
    for path in csv_paths:
        print(f"Saved time series: {path}", flush=True)
    if figure is not None:
        print(f"Saved figure: {prefix.parent / (prefix.name + '.png')}", flush=True)
    if final_figure is not None:
        print(
            f"Saved final amplitude figure: "
            f"{prefix.parent / (prefix.name + '-final-amplitude.png')}",
            flush=True,
        )


if __name__ == "__main__":
    main()
