"""Reanalyze saved long-time amplitude scans with a measured axion linewidth."""

from __future__ import annotations

import argparse
import csv
import json
import sys
import textwrap
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import matplotlib

if "--show" not in sys.argv:
    matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from astropy import units as unit

from axionbloch.constants import gamma_Xe129N
from axionbloch.MilkyWayAxionHalo import MilkyWayAxionHalo
from axionbloch.dependency import ppm


OUTPUT_DIR = SCRIPT_DIR / "outputs"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-prefix",
        type=Path,
        default=OUTPUT_DIR / "long-time-signal-amplitude-selected",
    )
    parser.add_argument(
        "--output-prefix",
        type=Path,
        default=OUTPUT_DIR / "long-time-signal-amplitude-selected-reanalyzed",
    )
    parser.add_argument(
        "--case",
        choices=("non-grad", "grad_perp", "grad_par"),
        default="grad_perp",
    )
    parser.add_argument("--alpha-deg", type=float, default=0.0)
    parser.add_argument("--num-frequency-points", type=int, default=50001)
    parser.add_argument("--frequency-span-ppm", type=float, default=10.0)
    parser.add_argument("--show", action="store_true")
    return parser.parse_args()


def add_script_watermark(fig: matplotlib.figure.Figure) -> None:
    text = "Generated by: " + str(Path(__file__).resolve())
    fig.text(
        0.01,
        0.01,
        textwrap.fill(text, width=120),
        ha="left",
        va="bottom",
        fontsize=6,
        color="0.45",
    )


def measure_tau(args: argparse.Namespace, frequency_Hz: float) -> dict[str, float]:
    axion = MilkyWayAxionHalo(nu_a=frequency_Hz * unit.Hz)
    frequencies = axion.makeLineshapeFrequencyGrid(
        frequency_span_ppm=args.frequency_span_ppm,
        num_frequency_points=args.num_frequency_points,
    )
    lineshape = axion.axion_lineshape(
        axion.v_0,
        axion.v_lab,
        axion.nu_a,
        frequencies,
        case=args.case,
        alpha=args.alpha_deg * unit.deg,
    )
    fwhm = axion.measureLineshapeFWHM(frequencies, lineshape, nu_a=axion.nu_a)
    return {
        "case": args.case,
        "alpha_deg": args.alpha_deg,
        "v_0_km_s": axion.v_0.to_value(unit.km / unit.s),
        "v_lab_km_s": axion.v_lab.to_value(unit.km / unit.s),
        "nominal_FWHM_ppm": axion.FWHM_a.to_value(ppm),
        "measured_FWHM_ppm": fwhm["FWHM_a"].to_value(ppm),
        "measured_tau_a_s": fwhm["tau_a"].to_value(unit.s),
    }


def signal_formula_values(
    time_s: np.ndarray,
    gamma,
    B_rms_T: float,
    tau_a_s: float,
    T2star_s: float,
) -> tuple[np.ndarray, float, float]:
    tau_a = tau_a_s * unit.s
    T2star = T2star_s * unit.s
    x_original = 0.5 * (
        1.0 + (tau_a / (tau_a + T2star)).to_value(unit.one)
    )
    time = time_s * unit.s
    buildup = (
        1.0 - np.exp(-(time / (x_original * T2star)).to_value(unit.one))
    ) ** x_original
    asymptotic = (
        np.abs(gamma)
        * (B_rms_T * unit.T)
        * T2star
        * np.sqrt((tau_a / (tau_a + T2star)).to_value(unit.one))
    ).to_value(unit.rad)
    return buildup * asymptotic, float(asymptotic), float(x_original)


def load_csv(path: Path) -> dict[str, np.ndarray]:
    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        rows = list(reader)
    return {
        key: np.array([float(row[key]) for row in rows])
        for key in reader.fieldnames
    }


def main() -> None:
    args = parse_args()
    summary_path = args.input_prefix.parent / f"{args.input_prefix.name}-summary.json"
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    if not summary["results"]:
        raise ValueError(f"No results in {summary_path}")

    frequency_Hz = summary["results"][0]["frequency_Hz"]
    tau_info = measure_tau(args, frequency_Hz)
    tau_a_s = tau_info["measured_tau_a_s"]
    reanalyzed = []

    fig, axes = plt.subplots(
        len(summary["results"]),
        1,
        figsize=(7.2, 2.5 * len(summary["results"])),
        constrained_layout=True,
        squeeze=False,
    )

    for result, ax in zip(summary["results"], axes[:, 0]):
        old_multiplier = result["T2star_over_taua"]
        csv_tag = f"T2star-{old_multiplier:g}taua".replace(".", "p")
        csv_path = args.input_prefix.parent / f"{args.input_prefix.name}-{csv_tag}.csv"
        series = load_csv(csv_path)
        expected, asymptotic, x_original = signal_formula_values(
            series["time_s"],
            gamma_Xe129N,
            result["B_rms_T"],
            tau_a_s,
            result["T2star_s"],
        )
        corrected_ratio = result["T2star_s"] / tau_a_s
        reanalyzed_result = {
            **{
                key: value
                for key, value in result.items()
                if key
                not in {
                    "T2star_over_taua",
                    "tau_a_s",
                    "x_original",
                    "final_expected",
                    "asymptotic_expected",
                }
            },
            "old_T2star_over_tau_a_est": old_multiplier,
            "corrected_T2star_over_tau_a": corrected_ratio,
            "tau_a_s": tau_a_s,
            "x_original": x_original,
            "final_expected": float(expected[-1]),
            "asymptotic_expected": asymptotic,
            "final_rms_over_expected": float(result["final_rms"] / expected[-1]),
        }
        reanalyzed.append(reanalyzed_result)

        ax.plot(
            series["time_s"],
            series["rms"],
            color="black",
            linewidth=1.2,
            label="simulation RMS",
        )
        step = max(1, int(np.ceil(len(series["time_s"]) / 80)))
        ax.errorbar(
            series["time_s"][::step],
            series["rms"][::step],
            yerr=series["signal_std"][::step],
            fmt="none",
            ecolor="tab:blue",
            elinewidth=0.8,
            alpha=0.45,
            capsize=1.5,
            label="std of signal",
        )
        ax.plot(
            series["time_s"],
            expected,
            color="tab:orange",
            linestyle="--",
            linewidth=1.3,
            label="formula, measured linewidth",
        )
        ax.set_title(
            rf"$T_2^*/\tau_a={corrected_ratio:.3g}$ "
            rf"(old label {old_multiplier:g}), $\tau_a={tau_a_s:.3g}$ s"
        )
        ax.set_xlabel("time (s)")
        ax.set_ylabel(r"$M_\perp/M_\mathrm{eqb}$")
        ax.grid(alpha=0.25)
        ax.legend(fontsize=8)

    add_script_watermark(fig)
    args.output_prefix.parent.mkdir(parents=True, exist_ok=True)
    time_plot_path = args.output_prefix.parent / f"{args.output_prefix.name}.png"
    fig.savefig(time_plot_path, dpi=220, facecolor="white")

    final_fig, final_ax = plt.subplots(figsize=(6.4, 4.2), constrained_layout=True)
    ratios = np.array([item["corrected_T2star_over_tau_a"] for item in reanalyzed])
    final_rms = np.array([item["final_rms"] for item in reanalyzed])
    final_std = np.array([item["final_std"] for item in reanalyzed])
    final_expected = np.array([item["asymptotic_expected"] for item in reanalyzed])
    order = np.argsort(ratios)
    final_ax.plot(
        ratios[order],
        final_expected[order],
        color="tab:orange",
        linestyle="--",
        marker="o",
        label="formula, measured linewidth",
    )
    final_ax.errorbar(
        ratios,
        final_rms,
        yerr=final_std,
        fmt="o",
        color="black",
        ecolor="tab:blue",
        capsize=2,
        label="simulation final RMS",
    )
    final_ax.set_xscale("log")
    final_ax.set_xlabel(r"$T_2^*/\tau_a$")
    final_ax.set_ylabel(r"final $M_\perp/M_\mathrm{eqb}$")
    final_ax.grid(alpha=0.25, which="both")
    final_ax.legend(fontsize=8)
    add_script_watermark(final_fig)
    final_plot_path = (
        args.output_prefix.parent / f"{args.output_prefix.name}-final-amplitude.png"
    )
    final_fig.savefig(final_plot_path, dpi=220, facecolor="white")

    out_summary_path = (
        args.output_prefix.parent / f"{args.output_prefix.name}-summary.json"
    )
    out_summary_path.write_text(
        json.dumps(
            {
                "tau_measurement": tau_info,
                "source_summary": str(summary_path),
                "results": reanalyzed,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    if args.show:
        plt.show()
    else:
        plt.close(fig)
        plt.close(final_fig)

    print(f"Measured tau_a = {tau_a_s:.6g} s")
    print(f"Saved reanalyzed time plot: {time_plot_path}")
    print(f"Saved reanalyzed final plot: {final_plot_path}")
    print(f"Saved reanalyzed summary: {out_summary_path}")
    for item in reanalyzed:
        print(
            f"old {item['old_T2star_over_tau_a_est']:g} -> "
            f"corrected {item['corrected_T2star_over_tau_a']:.6g}; "
            f"final/formula={item['final_rms_over_expected']:.6g}"
        )


if __name__ == "__main__":
    main()
